Repository intuit/Ignite, pull requests merged in 2018-09, with the labels that each got.

#52 load png logos correctly
  build-utils/webpack.config.production.js
  src/app/components/Header/index.js
  webpack.config.js
Labels: patch

#54 Sidebar Bugs
  src/app/components/Sidebar/index.js
  src/app/components/Sidebar/sidebar.css
  src/app/components/__tests__/__snapshots__/sidebar.test.js.snap
Labels: patch

#55 Peer deps
  .babelrc.js
  package.json
  src/app/components/App/app.css
  src/app/components/Header/index.js
  src/app/components/NavItem/index.js
  src/app/components/Sidebar/index.js
  src/extensions/front-matter-render/index.js
  src/ignite.js
  src/loaders/html-to-react.js
  src/utils/__tests__/__snapshots__/print-error.test.js.snap
  yarn.lock
Labels: patch

#56 opn browser if script fails
  package.json
  src/ignite.js
  yarn.lock
Labels: patch

#57 Sidebar
  automation/__tests__/basic.test.js
  src/app/components/App/app.css
  src/app/components/DocsPage/docs-page.css
  src/app/components/Header/header.css
  src/app/components/Router/index.js
  src/app/components/Sidebar/index.js
  src/app/components/Sidebar/sidebar.css
  src/app/components/__tests__/__snapshots__/router.test.js.snap
  src/app/components/__tests__/__snapshots__/sidebar.test.js.snap
  src/index.html
Labels: patch

#58 Jumping header
  src/app/components/Header/header.css
  src/app/components/__tests__/__snapshots__/header.test.js.snap
Labels: patch

#59 fix back ticks in code blocks by marking them with __BACK_TICK__
  src/extensions/jsx-fence/index.js
  src/loaders/__tests__/__snapshots__/html-to-react.test.js.snap
  src/loaders/__tests__/html-to-react.test.js
  src/loaders/html-to-react.js
Labels: patch

#64 Update README.md
  README.md
Labels: internal

#69 Add support for publishing to custom domains on GitHub pages
  src/ignite.js
Labels: minor
